### ISSUE TITLE
Possible Bean Creation Order Problem

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-java-dsl#119]
See https://travis-ci.org/spring-projects/spring-integration-samples/builds/161442417

The `fileOut.handler` bean is declared in the previous `IntegrationFlow` but, for some reason on Travis, the bean is not present. Gradle build works fine for me.

``````
20:16:18.357 [DEBUG] [TestEventLogger]     20:16:18.356 [Test worker] WARN  o.s.w.c.s.GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'markers' defined in org.springframework.integration.samples.filesplit.Application: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.integration.handler.ServiceActivatingHandler#0': Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'fileOut.handler' is defined
20:16:18.496 [DEBUG] [TestEventLogger]     20:16:18.476 [Test worker] ERROR o.s.boot.SpringApplication - Application startup failed
20:16:18.496 [DEBUG] [TestEventLogger]     org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'markers' defined in org.springframework.integration.samples.filesplit.Application: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.integration.handler.ServiceActivatingHandler#0': Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'fileOut.handler' is defined
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
20:16:18.499 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
20:16:18.500 [DEBUG] [TestEventLogger]      at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
20:16:18.501 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
20:16:18.513 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
20:16:18.513 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
20:16:18.514 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
20:16:18.514 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
20:16:18.515 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
20:16:18.515 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
20:16:18.516 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
20:16:18.516 [DEBUG] [TestEventLogger]      at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
20:16:18.517 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
20:16:18.517 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
20:16:18.518 [DEBUG] [TestEventLogger]      at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
20:16:18.518 [DEBUG] [TestEventLogger]      at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
20:16:18.526 [DEBUG] [TestEventLogger]      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
20:16:18.527 [DEBUG] [TestEventLogger]      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
20:16:18.527 [DEBUG] [TestEventLogger]      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
20:16:18.528 [DEBUG] [TestEventLogger]      at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
20:16:18.528 [DEBUG] [TestEventLogger]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:16:18.529 [DEBUG] [TestEventLogger]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:16:18.529 [DEBUG] [TestEventLogger]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:16:18.530 [DEBUG] [TestEventLogger]      at java.lang.reflect.Method.invoke(Method.java:483)
20:16:18.530 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
20:16:18.532 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
20:16:18.533 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
20:16:18.533 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
20:16:18.535 [DEBUG] [TestEventLogger]      at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
20:16:18.535 [DEBUG] [TestEventLogger]      at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
20:16:18.536 [DEBUG] [TestEventLogger]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:16:18.536 [DEBUG] [TestEventLogger]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:16:18.537 [DEBUG] [TestEventLogger]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:16:18.537 [DEBUG] [TestEventLogger]      at java.lang.reflect.Method.invoke(Method.java:483)
20:16:18.538 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
20:16:18.539 [DEBUG] [TestEventLogger]      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
20:16:18.539 [DEBUG] [TestEventLogger]      at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
20:16:18.540 [DEBUG] [TestEventLogger]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
20:16:18.540 [DEBUG] [TestEventLogger]      at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
20:16:18.541 [DEBUG] [TestEventLogger]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:16:18.546 [DEBUG] [TestEventLogger]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:16:18.546 [DEBUG] [TestEventLogger]      at java.lang.Thread.run(Thread.java:745)
20:16:18.547 [DEBUG] [TestEventLogger]     Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.integration.handler.ServiceActivatingHandler#0': Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'fileOut.handler' is defined
20:16:18.548 [DEBUG] [TestEventLogger]      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
20:16:18.548 [DEBUG] [TestEventLogger]      at ```
``````

**Comment by artembilan** [comment]
Well, looks we have a code like:
```
.handle(..., 
         e -> e.id("fileOut"));
...
.handle("fileOut.handler", "trigger")
```
where the last one is `BeanNameMessageProcessor` with the guilty code like:
```
public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
	Assert.notNull(beanFactory);
	Object target = beanFactory.getBean(this.object);
	this.delegate = new MethodInvokingMessageProcessor<T>(target, this.methodName);
}
```
That is a know "early BeanFactory access" issue. 
I think the best fix would be `SmartInitializingSingleton`.

**Comment by garyrussell** [comment]
Cool - it would be interesting to figure out why it only fails in travis - the previous bean should have been processed already. But it still should be fixed.

**Comment by artembilan** [comment]
Well, you see it is a problem on Linux. I saw similar problem many years ago. Looks like method order is somehow different on that OS.

**Comment by garyrussell** [comment]
Yes; it fails for me on my Linux machine.

**Comment by artembilan** [comment]
Good, so we don't have choice in that your sample unless move `Files.outboundAdapter()` to the separate top level `@Bean`.

**Comment by artembilan** [comment]
This must be backported to `1.1.x`.
