### ISSUE TITLE
Getting a Integration Flows can not be scoped beans message with 1.2.0.M1

### ISSUE THREAD

**Issue by bijukunjummen** [spring-projects/spring-integration-java-dsl#127]
Hello again Artem, I am not entire sure if this is an issue in my particular environment - debugged a little but could not make out for sure. I am seeing this message show up with Spring Integration Java DSL 1.2.0.M1(not with prior versions). I can understand the error specifically for IntegrationFlow beans, but this specific issue is being raised on a bean not related to Integration flows. Can you please check and let me know if this is a bug or if I am missing anything on my side.

```java
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'scopedTarget.eurekaClient': IntegrationFlows can not be scoped beans. Any dependant beans are registered as singletons, meanwhile Integratio
nFlow is just a logical container for them. 
Consider to use [IntegrationFlowContext] for manual registration of IntegrationFlows.
        at org.springframework.integration.dsl.config.IntegrationFlowBeanPostProcessor.afterSingletonsInstantiated(IntegrationFlowBeanPostProcessor.java:119)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:796)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
   ...
```

**Comment by artembilan** [comment]
Yeah... Hello  Biju!

The issue has been spotted today and fixed already: https://github.com/spring-projects/spring-integration-java-dsl/issues/120.

All what you need is the latest `1.2.0.BUILD-SNAPSHOT`.

Having such a problem, I'm going to release `RC1` this Friday.

Closing this a duplicated.

Cheers!

**Comment by bijukunjummen** [comment]
Awesome 👍 , thanks, will pick up RC1.
