### ISSUE TITLE
Maybe conflict with integration core!

### ISSUE THREAD

**Issue by schua1** [spring-projects/spring-integration-java-dsl#155]
Hi guys,

I use spring boot (version 2.0.0.RELEASE) with integration (version 5.0.3.RELEASE) to read data from csv files and post to restful web service. According to the reference manual, it is said file data could be transform into string by instruction `.transform(Transformers.fileToString())`.
However, above instruction need additional dependency of spring-integration-java-dsl (version 1.2.3.RELEASE) which is not managed by spring-boot yet. I have also configured a retry flow as http outbound gateway advisor. When I try to start up the spring boot application, I get BeanCreationException and the root cause is `java.lang.NoSuchMethodError: org.springframework.integration.dsl.StandardIntegrationFlow.isRegisterComponents()Z`. I could found two implementations of StandardIntegrationFlow, one is in core and other is in java-dsl.
My pom file is as following.
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
  	<groupId>org.springframework.boot</groupId>
  	<artifactId>spring-boot-starter-parent</artifactId>
  	<version>2.0.0.RELEASE</version>
  </parent>

  <groupId>com.fullway.care</groupId>
  <artifactId>longcare-submitter</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>longcare-submitter</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <executable>true</executable>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
  	<dependency>
  		<groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-integration</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.springframework.integration</groupId>
  		<artifactId>spring-integration-java-dsl</artifactId>
  		<version>1.2.3.RELEASE</version>
  	</dependency>
    <dependency>
        <groupId>org.springframework.integration</groupId>
        <artifactId>spring-integration-file</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.integration</groupId>
        <artifactId>spring-integration-http</artifactId>
    </dependency>
  	<dependency>
  		<groupId>com.jayway.jsonpath</groupId>
  		<artifactId>json-path</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.httpcomponents</groupId>
  		<artifactId>httpclient</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>com.fasterxml.jackson.core</groupId>
  		<artifactId>jackson-databind</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-logging</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-test</artifactId>
  		<scope>test</scope>
  	</dependency>
  </dependencies>
</project>
```
and my application file is as following.
```
@SpringBootApplication
@EnableScheduling
@EnableIntegration
public class SubmitterApplication {

   public static void main(String[] args) {
        new SpringApplicationBuilder(SubmitterApplication.class).web(WebApplicationType.NONE).run(args);
    }

    @Bean
    public Jackson2JsonObjectMapper objectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        objectMapper.enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL);
        objectMapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
        
        return new Jackson2JsonObjectMapper(objectMapper);
    }

    @Bean
    public RestTemplate restTemplate() {

        HttpClientBuilder httpClientBuilder = HttpClients.custom();
        httpClientBuilder.setDefaultRequestConfig(RequestConfig.custom()
                                                               .setSocketTimeout(timeout)
                                                               .setConnectTimeout(timeout)
                                                               .setConnectionRequestTimeout(timeout)
                                                               .setRedirectsEnabled(true)
                                                               .build())
                         .setDefaultCookieStore(new BasicCookieStore());
        CloseableHttpClient httpClient = httpClientBuilder.build();

        List<HttpMessageConverter<?>> messageConverters = new ArrayList<HttpMessageConverter<?>>();
        messageConverters.add(new FormHttpMessageConverter());
        messageConverters.add(new StringHttpMessageConverter());
        messageConverters.add(new MappingJackson2HttpMessageConverter());

        // initial restTemplate by logging into target server
        RestTemplate restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory(httpClient));
        restTemplate.setMessageConverters(messageConverters);

        return restTemplate;
    }

    @Bean
    public RequestHandlerRetryAdvice retrier() {
        RetryTemplate retryTemplate = new RetryTemplate();
        ExponentialBackOffPolicy backOffPolicy = new ExponentialBackOffPolicy();
        backOffPolicy.setInitialInterval(1000);
        backOffPolicy.setMaxInterval(timeout * 2);
        backOffPolicy.setMultiplier(5.0);
        retryTemplate.setBackOffPolicy(backOffPolicy);
        RetryPolicy retryPolicy = new SimpleRetryPolicy(4);
        retryTemplate.setRetryPolicy(retryPolicy);

        ErrorMessageSendingRecoverer emsr = new ErrorMessageSendingRecoverer(errorLoggingChannel());

        RequestHandlerRetryAdvice retrier = new RequestHandlerRetryAdvice();
        retrier.setRetryTemplate(retryTemplate);
        retrier.setRecoveryCallback(emsr);

        return retrier;
    }

    @Bean
    public MessageChannel errorLoggingChannel() {
        return MessageChannels.direct("errorLoggingChannel").get();
    }

    @Bean
    public LoggingHandler errorLoggingHandler() {
        LoggingHandler handler = new LoggingHandler(LoggingHandler.Level.ERROR);
        handler.setShouldLogFullMessage(true);
        return handler;
    }
    
    @Bean
    public IntegrationFlow errorLoggingFlow() {
        return IntegrationFlows.from("errorLoggingChannel").handle(errorLoggingHandler()).get();
    }

    @Bean
    public IntegrationFlow readDataFilesFlow() {
        return IntegrationFlows.from(Files.inboundAdapter(new File(dataFileFolder))
                                          .regexFilter("^*.csv$")
                                          .preventDuplicates(true))
                               .transform(Transformers.fileToString("UTF-8"))
                               .enrichHeaders(...)
                               .get();
    }
}
```
The stack trace as following.
```
20:03:08.901 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'errorLoggingFlow' defined in com.fullway.care.longcare.submitter.SubmitterApplication: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.integration.dsl.StandardIntegrationFlow.isRegisterComponents()Z
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.fullway.care.longcare.submitter.SubmitterApplication.main(SubmitterApplication.java:137)
Caused by: java.lang.NoSuchMethodError: org.springframework.integration.dsl.StandardIntegrationFlow.isRegisterComponents()Z
	at org.springframework.integration.dsl.config.IntegrationFlowBeanPostProcessor.processStandardIntegrationFlow(IntegrationFlowBeanPostProcessor.java:139)
	at org.springframework.integration.dsl.config.IntegrationFlowBeanPostProcessor.postProcessBeforeInitialization(IntegrationFlowBeanPostProcessor.java:100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
	... 13 common frames omitted
```

**Comment by artembilan** [comment]
Starting with Spring Integration `5.0` you don't need an extra dependency for Java DSL. It's already a part of the Core project. And right, this project is not compatible with Spring Integration `5.0`.

See [Reference Manual](https://github.com/spring-projects/spring-integration-java-dsl/wiki/Spring-Integration-Java-DSL-Reference):

> This project has been absorbed by Spring Integration Core starting with version 5.0. Please consult its Reference Manual for the actual documentation. This project is only in a maintenance, bug fixing state. 

And [Migration Guide](https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-4.3-to-5.0-Migration-Guide).

**Comment by schua1** [comment]
Many thanks for your reply.
However, it seems the Transformers.fileToString() is not available yet. I declear a FileToStringTransformer bean directly as a walkaround solution.
The example code in reference manual in section "Configuring with the Java DSL" under chapter 15.2 Reading Files should be updated properly.
