### ISSUE TITLE
Make 1.0.x version compatible with Platform 1.1.x and release 1.0.2

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration-java-dsl#35]
Do the same for `master`.

**Comment by artembilan** [comment]
Fro example:
```
Caused by: java.lang.NoSuchMethodError: org.springframework.integration.mail.MailSendingMessageHandler.<init>(Lorg/springframework/mail/javamail/JavaMailSender;)V
    at org.springframework.integration.dsl.mail.MailSendingMessageHandlerSpec.<init>(MailSendingMessageHandlerSpec.java:39)
    at org.springframework.integration.dsl.mail.Mail.outboundAdapter(Mail.java:27)
    at org.springframework.integration.dsl.Adapters.mail(Adapters.java:155)
    at org.springframework.integration.dsl.test.mail.MailTests$ContextConfiguration.lambda$sendMailFlow$114(MailTests.java:204)
    at org.springframework.integration.dsl.test.mail.MailTests$ContextConfiguration$$Lambda$145/1331089092.apply(Unknown Source)
    at org.springframework.integration.dsl.IntegrationFlowDefinition.handleWithAdapter(IntegrationFlowDefinition.java:479)
    at org.springframework.integration.dsl.test.mail.MailTests$ContextConfiguration.sendMailFlow(MailTests.java:204)
    at org.springframework.integration.dsl.test.mail.MailTests$ContextConfiguration$$EnhancerBySpringCGLIB$$aa1b7aa6.CGLIB$sendMailFlow$2(<generated>)
    at 
```

**Comment by artembilan** [comment]
Merged and release.
Waiting for the fix from Bintray for promotion to Central
